require("wienio.lazy")
require("wienio.plugins.telescope")
require("wienio.plugins.dressing")
require("wienio.plugins.nvim-cmp")
require("wienio.plugins.lsp.mason")
require("wienio.plugins.lsp.lspconfig")
require("wienio.plugins.toggleterm")
require("wienio.plugins.setup.options")
require("wienio.plugins.setup.keymap")
require("wienio.plugins.treesitter")
require("wienio.plugins.neoscroll")
require("wienio.plugins.autopairs")
require("wienio.plugins.tailwindcss-colorizer-cmp")
require("wienio.plugins.lualine")

